query GetMyProjects @auth(level: USER) {
  projects(where: { ownerId: { eq_expr: "auth.uid" } }) {
    id
    name
    description
    isTeamProject
    createdAt
    lastModifiedAt
    owner {
      displayName
      email
    }
  }
}

mutation CreateNewProject($name: String!, $isTeamProject: Boolean!, $description: String) @auth(level: USER) {
  project_insert(
    data: {
      name: $name
      isTeamProject: $isTeamProject
      description: $description
      ownerId_expr: "auth.uid"
      createdAt_expr: "request.time"
    }
  )
}

query GetTeamDetails($teamId: UUID!) @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users as team access is handled by ProjectAccess and TeamMembership checks.") {
  team(id: $teamId) {
    id
    name
    description
    createdAt
    owner {
      displayName
    }
    teamMemberships_on_team {
      role
      user {
        displayName
        email
      }
    }
    projects_on_team {
      id
      name
      isTeamProject
    }
  }
}

mutation UpdateFileContent($fileId: UUID!, $newContent: String!) @auth(level: USER) {
  file_update(
    key: { id: $fileId }
    data: {
      content: $newContent
      updatedAt_expr: "request.time"
    }
  )
}