type User @table {
  displayName: String!
  email: String!
  createdAt: Timestamp!
  photoUrl: String
  lastLoginAt: Timestamp
}

type Project @table {
  name: String!
  isTeamProject: Boolean!
  createdAt: Timestamp!
  description: String
  lastModifiedAt: Timestamp
  owner: User
  team: Team
}

type File @table {
  name: String!
  content: String!
  language: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  filePath: String
  project: Project
}

type Team @table {
  name: String!
  owner: User!
  createdAt: Timestamp!
  description: String
}

type TeamMembership @table(key: ["user", "team"]) {
  role: String!
  joinedAt: Timestamp!
  user: User!
  team: Team!
}

type ProjectAccess @table(key: ["project", "user"]) {
  permissionLevel: String!
  grantedAt: Timestamp!
  project: Project!
  user: User!
}